from AirCManager import *




CHAMBRE1 = "CHAMBRE1"
CHAMBRE2 = "CHAMBRE2"
CHAMBRE3 = "CHAMBRE3"
DREAMROOM = "DREAMROOM"
SALON = "SALON"
ETAGE = "ETAGE"


roomList = {}


MQTT_ESP_AERAULIC_STATE = "AC/ESP/AERAULIC_STATE"
MQTT_ESP_INIT_DONE = "AC/ESP/INIT_DONE"
    
MQTT_ADDRESS = {}
MQTT_ADDRESS[CHAMBRE1]  = "zigbee2mqtt/0x00158d00083070f8T"
MQTT_ADDRESS[CHAMBRE2] 	= "zigbee2mqtt/0x00158d000830347fT"
MQTT_ADDRESS[CHAMBRE3] 	= "zigbee2mqtt/0x00158d0008303b34T"
MQTT_ADDRESS[DREAMROOM] = "zigbee2mqtt/0x00158d0006d41ce1T" 
MQTT_ADDRESS[SALON] 	= "zigbee2mqtt/0x00158d0007f2a0d9T"
MQTT_ADDRESS[ETAGE] 	= "zigbee2mqtt/0x00158d0007f2a489T"

MQTT_TO_ROOM = {}
MQTT_TO_ROOM[MQTT_ADDRESS[CHAMBRE1]] 	= CHAMBRE1
MQTT_TO_ROOM[MQTT_ADDRESS[CHAMBRE2]] 	= CHAMBRE2
MQTT_TO_ROOM[MQTT_ADDRESS[CHAMBRE3]]	= CHAMBRE3
MQTT_TO_ROOM[MQTT_ADDRESS[DREAMROOM]] 	= DREAMROOM
MQTT_TO_ROOM[MQTT_ADDRESS[SALON]] 	= SALON
MQTT_TO_ROOM[MQTT_ADDRESS[ETAGE]] 	= ETAGE





MQTT_SUFFIX_TARGETTEMP = "targettemp"
MQTT_SUFFIX_AC_STATE = "state"
MQTT_PREFIX = "AC"
AC_STATE_ON = 2
AC_STATE_OFF = 1


def getRoomFromAddress(address):
    for name in roomList:
        if(address.find(name) != -1):
            print("Found room in address : " + name + "\n")
            return name
	
